question_data = [
    {"response_code": 0, "results":
        [{"type":"boolean","difficulty":"medium","category":"Entertainment: Video Games","question":"Resident Evil 4 was originally meant to be a Nintendo GameCube exclusive.","correct_answer":"True","incorrect_answers":["False"]},
         {"type":"boolean","difficulty":"medium","category":"Sports","question":"In 2008, Usain Bolt set the world record for the 100 meters with one shoelace untied.","correct_answer":"True","incorrect_answers":["False"]},
         {"type":"boolean","difficulty":"medium","category":"Mythology","question":"The Roman god &quot;Jupiter&quot; was first known as &quot;Zeus&quot; to the Greeks.","correct_answer":"True","incorrect_answers":["False"]},
         {"type":"boolean","difficulty":"medium","category":"Vehicles","question":"The Chevrolet Corvette has always been made exclusively with V8 engines only.","correct_answer":"False","incorrect_answers":["True"]},
         {"type":"boolean","difficulty":"medium","category":"Entertainment: Television","question":"In &quot;Star Trek&quot;, Klingons are commonly referred to as &quot;Black Elves&quot;.","correct_answer":"False","incorrect_answers":["True"]},
         {"type":"boolean","difficulty":"medium","category":"Entertainment: Video Games","question":"In the game &quot;Until Dawn&quot; Emily is the only playable character who can be killed by another playable character directly.","correct_answer":"True","incorrect_answers":["False"]},
         {"type":"boolean","difficulty":"medium","category":"Entertainment: Television","question":"In the TV series Red Dwarf, Kryten&#039;s full name is Kryten 2X4B-523P.","correct_answer":"True","incorrect_answers":["False"]},
         {"type":"boolean","difficulty":"medium","category":"History","question":"&quot;I disapprove of what you say, but I will defend to the death your right to say it&quot; is a quote from French philosopher Voltaire.","correct_answer":"False","incorrect_answers":["True"]},
         {"type":"boolean","difficulty":"medium","category":"Science: Computers","question":"Linus Sebastian is the creator of the Linux kernel, which went on to be used in Linux, Android, and Chrome OS.","correct_answer":"False","incorrect_answers":["True"]},
         {"type":"boolean","difficulty":"medium","category":"Geography","question":"Liechtenstein does not have an airport.","correct_answer":"True","incorrect_answers":["False"]}]}
    ]